Tests full:
  $ explode-js run --deterministic test_vfunexported.json
  â”€â”€ PHASE 1: TEMPLATE GENERATION â”€â”€
  âœ” Loaded: test_vfunexported.json
  âš’ Generating 1 template(s):
  â”œâ”€â”€ ðŸ“„ ./symbolic_test_0.js
  
  â”€â”€ PHASE 2: ANALYSIS & VALIDATION â”€â”€
  â—‰ [1/1] Procesing ./symbolic_test_0.js
  â”œâ”€â”€ Symbolic execution output:
  Exec failure: x
  â”œâ”€â”€ âš  Detected 1 issue(s)!
  â”‚   â”œâ”€â”€ â†º Replaying 2 test case(s)
  â”‚   â”‚   â”œâ”€â”€ ðŸ“„ [1/2] Using test case: ./symbolic_test_0/test-suite/witness-0.json
  â”‚   â”‚   â”‚   â”œâ”€â”€ Node exited with 0
  â”‚   â”‚   â”‚   â””â”€â”€ âœ” Status: Success (created file "./success")
  â”‚   â”‚   â”œâ”€â”€ ðŸ“„ [2/2] Using test case: ./symbolic_test_0/test-suite/witness-1.json
  â”‚   â”‚   â”‚   â”œâ”€â”€ Node exited with 0
  â”‚   â”‚   â”‚   â””â”€â”€ âœ” Status: Success (created file "./success")

  $ explode-js run --deterministic test_usecase_4.json
  â”€â”€ PHASE 1: TEMPLATE GENERATION â”€â”€
  âœ” Loaded: test_usecase_4.json
  âš’ Generating 1 template(s):
  â”œâ”€â”€ ðŸ“„ ./symbolic_test_0.js
  
  â”€â”€ PHASE 2: ANALYSIS & VALIDATION â”€â”€
  â—‰ [1/1] Procesing ./symbolic_test_0.js
  â”œâ”€â”€ Symbolic execution output:
  "Uncaught TypeError"
  "Uncaught TypeError"
  "Uncaught TypeError"
  "Uncaught TypeError"
  "Uncaught TypeError"
  "Uncaught TypeError"
  "Uncaught TypeError"
  Abort: "Uncaught Error: I pollute."
  â”œâ”€â”€ âš  Detected 1 issue(s)!
  â”‚   â”œâ”€â”€ â†º Replaying 1 test case(s)
  â”‚   â”‚   â”œâ”€â”€ ðŸ“„ [1/1] Using test case: ./symbolic_test_0/test-suite/witness-0.json
  â”‚   â”‚   â”‚   â”œâ”€â”€ Node exited with 1
  â”‚   â”‚   â”‚   â””â”€â”€ âœ” Status: Success (threw Error("I pollute."))

  $ explode-js run --deterministic test_http_server.json
  â”€â”€ PHASE 1: TEMPLATE GENERATION â”€â”€
  âœ” Loaded: test_http_server.json
  âš’ Generating 1 template(s):
  
  â”€â”€ PHASE 2: ANALYSIS & VALIDATION â”€â”€
  â—‰ [1/1] Procesing ././test_http_server.js
  â”œâ”€â”€ Symbolic execution output:
  ReadFile failure: (str.++ ("./", request.url))
  â”œâ”€â”€ âš  Detected 1 issue(s)!
  â”‚   â”œâ”€â”€ â†º Replaying 1 test case(s)
  â”‚   â”‚   â”œâ”€â”€ ðŸ“„ [1/1] Using test case: ./test_http_server/test-suite/witness-0.json
  â”‚   â”‚   â”‚   â”œâ”€â”€ Node exited with 0
  â”‚   â”‚   â”‚   â””â”€â”€ âœ” Status: Success (undesired file access occurred)
